### PR TITLE
Thread safe

### PR DESCRIPTION
**Pull request by stevenkaras**
Various small fixes, and changed the lock granularity to threads.

### CODE REVIEW

**Comment by PatrickTulskie** [comment]
@stevenkaras This looks good from my quick review but I haven't had a chance to test it yet.  Having an absolutely insane week.  I'll do my best to get this merged in ASAP.  Anything in particular I should focus on when testing it?

**Comment by stevenkaras** [comment]
Nothing in particular comes to mind. I've been using the modifications in a
system with lots of lock contention (16 threads in 4 processes) and haven't
noticed anything too unusual. A good threaded test case is a good idea, but
I'm swamped for the next few days. If you don't get to it by the weekend
I'll put something together.

**Comment by PatrickTulskie** [comment]
I tried this out with a few things and it looked good to me.  I'm gonna push it out and bump the version.  Let me know if you come up with an official way to test this... I know testing threaded code can be tricky.

**Comment by PatrickTulskie** [comment]
Released 0.2.0 with these changes (and a shortened test suite).

**Pull request merged**
