### PR TITLE
Refactor a really large chunk of the codebase

### PR DESCRIPTION
**Pull request by joshuaclayton**
This is a general improvement pull request but also breaks existing APIs.
1. Got rid of Jeweler. Gemspecs aren't hard and introducing another gem dependency really isn't necessary.
2. Added bundler, since it's the de-facto standard for managing dependencies for gems
3. Fixed naming convention. The standard for gems is to use underscores instead of dashes for gem names, file names, etc.
4. Improved test coverage significantly. Not that it matters, but redis_lock.rb now has 100% C0 code coverage.
5. Changed constructor to accept an instance of redis and a key. Dependency injection feels a lot nicer here than reopening Redis and including a module.
6. Added a retry method that accepts an enumerable. Instead of just passing numbers to the constructor, assigning retries is handled with `RedisLock.new(redis, "my-key").retry(200.times).lock`.

I didn't change the authors, mess with the gemfile, change authors, or bump the version, so that can be done however you see fit. Although the repo should change names to redis_lock to honor the underscore, I don't think it's necessary since most people will be using the gem itself. It'd be nice though!

Additionally, I updated the readme to reflect the API changes and gave some common uses, with exception handling.

### CODE REVIEW

**Comment by PatrickTulskie** [comment]
Hey Josh.  I saw this and just haven't had a chance to formulate an articulate response.  The only thing keeping me from just merging it in is breaking the existing APIs and naming of the gem itself.

So, I think I'll likely pull in 1, 2, 4, and 5.  I like 6, but I'd like it if the API itself still functioned with an integer.  I'll take a look at adding some backwards compatibility.  For the bundler stuff - none of my projects use bundler.  I know this sounds kind of silly, but it's cost me more time than it's saved me so I just avoid it where I can.  I'm okay with using it here as long as it stays the hell out of my way.

As far as the naming convention (number 3)... I know the convention is gem_name, but most of the redis gems I looked at were redis-something so I just followed that.  In retrospect, this was probably a bad idea, but it is what it is and until RubyGems has some provision for renaming a gem then I'd rather keep it the way it is.

Thoughts?

**Comment by PatrickTulskie** [comment]
Actually, after looking through the code quickly, it doesn't look like I can cherry pick things so easily.  The naming stuff is in various commits and the retry logic rips out the whole concept of time and instead uses attempts.  I guess it would be trivial to simply pass an integer instead of an enumerator and do some quick type checking.  An Enumerator adds overhead where there wouldn't be any otherwise.  I just did a quick benchmark of your enumerator.to_a.last + 1 logic 200k times...

```
                user     system      total        real
Enumeration  0.930000   0.170000   1.100000 (  1.225930)
Integer      0.000000   0.000000   0.000000 (  0.000007)
```

The naming stuff... eh, I'll do another release under the old name with a post install notice and we can move on.  I don't want to throw the baby out with the bath water.

**Comment by joshuaclayton** [comment]
Yeah, I understand where you're coming from re: Bundler, and it does break the existing API. I thought about going it from the perspective of keeping the same API but that would require mixing in behavior to Redis, which I'm pretty adamant against doing. The enumerable stuff is definitely slow if you set it up to retry a bunch of times - for that benchmark, what did you end up passing in?

I'll keep my fork as a fork for now (since Bundler lets you point to git repositories for gems :-)), but thanks for taking a look at the pull request and giving your feedback - and for writing the code in the first place!

**Comment by PatrickTulskie** [comment]
Hey @joshuaclayton I know it's been a really long time but I'm gonna close this out.  If you want to get some of the stuff you have in your branch into canonical then let's do a few smaller feature branches so I can merge and test independently.

**Pull request closed without merging**
